#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Aug 29 17:57:16 2019
Project "Pathos"
@author: fcollins
"""

import sys
import time
import os 
import csv
import colorsys
import pandas as pd
import numpy as np
import math 
import psychopy 
import matplotlib
matplotlib.use("Agg")
from psychopy import event, core, logging, visual, data, gui
from psychopy.core import getTime
import pygame
from pygame.locals import *

from psychopy import locale_setup, sound, gui, visual, core, data, event, logging, clock
from psychopy.constants import (NOT_STARTED, STARTED, PLAYING, PAUSED, STOPPED,
                                FINISHED, PRESSED, RELEASED, FOREVER)
from numpy import (sin, cos, tan, log, log10, pi, average, 
                   sqrt, std, deg2rad, rad2deg, linspace, asarray)

surveyName = "Survey Information"
surveyInfo = {'id': ''}  #This is is called below and is needed for starting the GUI
dlg = gui.DlgFromDict(dictionary = surveyInfo, title = surveyName) #creat the GUI
if dlg.OK == False:
    core.quit() # user pressed cancel
surveyInfo['surveyName'] = surveyName  

subject_id = surveyInfo['id']
win = visual.Window(size =[800, 600], fullscr = False)

file_name = "BFAS-Self_Survey" + str(subject_id) + ".csv"
BFAS-Self_Survey = pd.read_csv('BFAS-Self_Survey.csv') 

win.flip()
message = visual.TextStim(win, text = 'press spacebar to begin')
message.setAutoDraw(True)
win.flip()
event.waitKeys(keyList='space')
message.setText('')
win.flip()

instruct = 'Here are a number of characteristics that may or may not describe you. For example, do you agree that you seldom feel blue, compared to most other people? Please fill in the number that best indicates the extent to which you agree or disagree with each statement listed below. Be as honest as possible, but rely on your initial feeling and do not think too much about each item."

instructions = visual.TextStim(win, text = instruct, 
                               units = 'norm')

sp_text = visual.TextStim(win, text = "pres the spacebar to continue",
                          height = .06, units = 'norm',
                          pos = (0.0, -0.7))


